### ISSUE TITLE
bindings error

### ISSUE THREAD

**Issue by huang-erbai** [node-ffi-napi/ref-napi#18]
![image](https://user-images.githubusercontent.com/50433365/61778052-9dc35c00-ae30-11e9-8712-7bca799e6788.png)

**Comment by huang-erbai** [comment]
what wrong about this?

**Comment by huang-erbai** [comment]
import * as ref from 'ref-napi';
import HelloWorld from '@/components/HelloWorld.vue';

const ffi = require('ffi-napi');

const { dialog } = require('electron').remote;

**Comment by colorpeach** [comment]
@huang-erbai I also encountered the same error, how did you solve it？
