### ISSUE TITLE
ref-napi No native build was found for platform=win32 arch=ia32

### ISSUE THREAD

**Issue by victor-thrifts** [node-ffi-napi/ref-napi#39]
Error: No native build was found for platform=win32 arch=ia32 runtime=node abi=72 uv=1 libc=glibc
    at Object../node_modules/ref-napi/lib/ref.js (D:\nodeWeb\angular-tour\dist\server\main.js:162130:111)
    at __webpack_require__ (D:\nodeWeb\angular-tour\dist\server\main.js:20:30)

 main.js context:

"use strict";

const assert = __webpack_require__(/*! assert */ "assert");
const inspect = __webpack_require__(/*! util */ "util").inspect;
const debug = __webpack_require__(/*! debug */ "./node_modules/debug/src/index.js")('ref');
const os = __webpack_require__(/*! os */ "os");
const path = __webpack_require__(/*! path */ "path");

exports = module.exports = __webpack_require__(/*! node-gyp-build */ "./node_modules/node-gyp-build/index.js")(path.join(__dirname, '..'));     //line 162130

this main.js file cames from my server.ts file:
import 'zone.js/dist/zone-node';

import { ngExpressEngine } from '@nguniversal/express-engine';
import * as express from 'express';
import { join } from 'path';
import { AppServerModule } from './src/main.server';
import { APP_BASE_HREF } from '@angular/common';
import { existsSync } from 'fs';

const ref = require('ref-napi');      //add this line. cause error. 

this project is a angular server side app.   (angular ssr demo found on angular.io), 
 i only add a line to this project. no luck.

my node version: 10.18.1   32bit
my angular version 9.0.0
OS :  WIN10. X64

**Comment by victor-thrifts** [comment]
it is a node_gyp  problem. i think.

**Comment by sqpdln** [comment]
did you have any luck on this? i'm having the same issue in electron.

**Comment by ngiafeno** [comment]
Did somebody find any reason why it doesn't work fine ? I'm having the same issue
