### ISSUE TITLE
dlopen error

### ISSUE THREAD

**Issue by antman1p** [node-ffi-napi/ref-napi#52]
I am developing an electron app and am trying to use `var $ = require('nodobjc')` and my console is throwing an error: 

`Uncaught Error: dlopen(/Users/Me/Documents/git/NodObjC/node_modules/ref-napi/prebuilds/darwin-x64/electron.napi.node, 1): Symbol not found: _napi_create_error
  Referenced from: /Users/Me/Documents/git/NodObjC/node_modules/ref-napi/prebuilds/darwin-x64/electron.napi.node
  Expected in: flat namespace
 in /Users/Me/Documents/git/NodObjC/node_modules/ref-napi/prebuilds/darwin-x64/electron.napi.node`

at ELECTRON_ASAR.js:173:

  ```
// Override APIs that rely on passing file path instead of content to C++.
  const overrideAPISync = function (module, name, arg) {
    if (arg == null) {
      arg = 0
    }
    const old = module[name]
    module[name] = function () {
      const p = arguments[arg]
      const [isAsar, asarPath, filePath] = splitPath(p)
      if (!isAsar) {
        return old.apply(this, arguments) // Line 173
      }

      const archive = getOrCreateArchive(asarPath)
      if (!archive) {
        invalidArchiveError(asarPath)
      }

      const newPath = archive.copyFileOut(filePath)
      if (!newPath) {
        notFoundError(asarPath, filePath)
      }

      arguments[arg] = newPath
      return old.apply(this, arguments) 
    }
  }
```

**Comment by addaleax** [comment]
Which Node.js/Electron version are you using?

**Comment by antman1p** [comment]
Node v14.15.4
Electron v1.4.13

**Comment by addaleax** [comment]
> Electron v1.4.13

Yeah that’s not going to work

**Comment by antman1p** [comment]
Updated to Electron v11.1.1.
