### ISSUE TITLE
Number as a callback pointer ?

### ISSUE THREAD

**Issue by Psycokwet** [node-ffi-napi/ref-napi#63]
Hello !

I'm using the bass library, from un4seen, in which, there is those definition : 

``` c
typedef DWORD (CALLBACK STREAMPROC)(HSTREAM handle, void *buffer, DWORD length, void *user);
/* User stream callback function.
handle : The stream that needs writing
buffer : Buffer to write the samples in
length : Number of bytes to write
user   : The 'user' parameter value given when calling BASS_StreamCreate
RETURN : Number of bytes written. Set the BASS_STREAMPROC_END flag to end the stream. */

#define BASS_STREAMPROC_END		0x80000000	// end of user stream flag

// special STREAMPROCs
#define STREAMPROC_DUMMY		(STREAMPROC*)0		// "dummy" stream
#define STREAMPROC_PUSH			(STREAMPROC*)-1		// push stream
#define STREAMPROC_DEVICE		(STREAMPROC*)-2		// device mix stream
#define STREAMPROC_DEVICE_3D	(STREAMPROC*)-3		// device 3D mix stream
```

As you can see, there is a function definition, STREAMPROC, which is used elsewhere in code as normal function pointer, but, that can be also used as a code, to use default function. Like, if we mention STREAMPROC_PUSH when calling a function made to treat a STREAMPROC, it will understand that it have to use a specific STREAMPROC, without having to really give a pointer to said callback.

Until now, i'm not sure either if ref-napi can allow me to give (STREAMPROC*)-1 as a parameter when calling a function, or how to do it if it's possible. I tried a bunch of stuff without any success.

Thank you for your input on this matter !

**Comment by Psycokwet** [comment]
Erf, I think I got an epiphany, I still don't have the full result I'm hoping for, but, I seems to no longer have the issue for which I opened the issue. Sorry for that. For now I'm going with an int64 ref.

**Comment by Kreijstal** [comment]
how did you solve this?

**Comment by Psycokwet** [comment]
As I mentioned in my last answer, I choose a completely different path, for which this issue was irrelevant, so, I don't have an answer to this, I'm sorry. Good luck ! :)
